const CustomerService = [
            {
                id: 1000,
                name: 'Nahimul islam naim',
                date: 'January,2015',
                status: 'Non Resident',
                room: 'C-140',
                department: 'Information and Communication Engineering',
                roll: '1911077121',
                mobile: '01774366602',
                fee: 'paid',
            },
            {
                id: 1001,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1002,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1003,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1004,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1005,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1000,
                name: 'Nahimul islam naim',
                date: 'January,2015',
                status: 'Non Resident',
                room: 'C-140',
                department: 'Information and Communication Engineering',
                roll: '1911077121',
                mobile: '01774366602',
                fee: 'paid',
            },
            {
                id: 1000,
                name: 'Nahimul islam naim',
                date: 'January,2015',
                status: 'Non Resident',
                room: 'C-140',
                department: 'Information and Communication Engineering',
                roll: '1911077121',
                mobile: '01774366602',
                fee: 'paid',
            },
            {
                id: 1001,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1002,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1003,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1004,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1005,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1000,
                name: 'Nahimul islam naim',
                date: 'January,2015',
                status: 'Non Resident',
                room: 'C-140',
                department: 'Information and Communication Engineering',
                roll: '1911077121',
                mobile: '01774366602',
                fee: 'paid',
            },
            {
                id: 1000,
                name: 'Nahimul islam naim',
                date: 'January,2015',
                status: 'Non Resident',
                room: 'C-140',
                department: 'Information and Communication Engineering',
                roll: '1911077121',
                mobile: '01774366602',
                fee: 'paid',
            },
            {
                id: 1001,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1002,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1003,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1004,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1005,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1000,
                name: 'Nahimul islam naim',
                date: 'January,2015',
                status: 'Non Resident',
                room: 'C-140',
                department: 'Information and Communication Engineering',
                roll: '1911077121',
                mobile: '01774366602',
                fee: 'paid',
            },
            {
                id: 1000,
                name: 'Nahimul islam naim',
                date: 'January,2015',
                status: 'Non Resident',
                room: 'C-140',
                department: 'Information and Communication Engineering',
                roll: '1911077121',
                mobile: '01774366602',
                fee: 'paid',
            },
            {
                id: 1001,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1002,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1003,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1004,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1005,
                name: 'James Butt',
                date: '2015-09-13',
                status: 'Non Resident',
                room: 'A-101',
                department: 'CSE',
                roll: '123456',
                mobile: '1234567890',
                fee: 'paid',
            },
            {
                id: 1000,
                name: 'Nahimul islam naim',
                date: 'January,2015',
                status: 'Non Resident',
                room: 'C-140',
                department: 'Information and Communication Engineering',
                roll: '1911077121',
                mobile: '01774366602',
                fee: 'paid',
            }
        ];
export default CustomerService;



